version: '3'

services:

    php-fpm:
        build:
            context: .
            dockerfile: .docker/php-fpm/Dockerfile
        container_name: php-fpm
        environment:
            PIMCORE_INSTALL_ADMIN_USERNAME: admin
            PIMCORE_INSTALL_ADMIN_PASSWORD: admin
            PIMCORE_INSTALL_MYSQL_USERNAME: pim_user
            PIMCORE_INSTALL_MYSQL_PASSWORD: qwerty12345
        volumes:
            - .:/var/www/html
        depends_on:
            -   database

    database:
        image: mysql:8.0
        container_name: database
        volumes:
            - ./.mysql-data:/var/lib/mysql/:rw
        environment:
            MYSQL_ROOT_PASSWORD: password

    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html:ro
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./.nginx-logs:/var/log/nginx:rw
        depends_on:
            - php-fpm